# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 19:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='object_id',
        ),
    ]
